title: Tamires Correa Marcal
description: Hi, I'm a Computational Neuroscientist and an AI Researcher 
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/img/head.jpeg
show_downloads: false
google_analytics: G-7KE1Y4QNRF
