title: Tamires Correa Marcal
description: Hi, I'm a Computational Neuroscients and an AI Researcher.
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/img/headshot_circle.jpg
#show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
