title: Tamires Correa Marcal
description: Hi, I'm a Computational Neuroscientist and an AI Researcher. | [Researcher at McGill Centre for Integrated Neuroscience](https://mcin.ca/ ) | [Fellow at Healthy Brains Healthy Lifes (HBHL)](https://www.mcgill.ca/hbhl/)
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/img/head.jpeg
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
