title: Tamires Correa Marcal
description: Hi, I'm a Computational Neuroscientist and an AI Researcher with a decade of experience bridging brain science and machine learning. With a strong background in science communication, industry collaboration, and open science, I am passionate about building tools that bring research closer to real-world solutions. I am currently pursuing a PhD at McGill University in the Integrated Program in Neuroscience at the Montreal Neurological Institute (MNI) and Montreal Institute for Learning Algorithms (MILA). I explore how the brain predicts and responds to real-world stimuli, combining predictive modeling, neuroimaging, and AI.
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/img/head.jpeg
show_downloads: false
google_analytics: G-7KE1Y4QNRF
